[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "nft"

[dev]
  command = "npm run dev"
  port = 3001